# Generated by Django 4.0.6 on 2022-07-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autopark', '0003_vehicle_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
    ]
